version: 2.1

jobs:
  deploy-function:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: lambda
      - run: ./1-create-bucket.sh
      - run: ./2-deploy.sh
      - run: ./3-invoke.sh

  test:
    docker:
      - image: circleci/openjdk:11-node
    steps:
      - checkout
      - run: mvn test

  build:
    docker:
      - image: circleci/openjdk:11-node
    steps:
      - checkout
      - run: mvn -Dmaven.test.skip=true package
      - store_artifacts:
          path: /target/restaurants-scraper-1.0-SNAPSHOT.jar
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: target
          # Must be relative path from root
          paths:
            - restaurants-scraper-1.0-SNAPSHOT.jar

orbs:
  aws-cli: circleci/aws-cli@1.3.0

workflows:
  version: 2

  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-function:
          requires:
            - test
          filters:
            branches:
              only: master