version: 2.1

references:
  restore_target: &restore_target
    restore_cache:
      keys:
        - $CACHE_KEY
  cache_target: &cache_target
    save_cache:
      key: $CACH_KEY
      paths:
        - target/

jobs:
  deploy-function:
    executor: aws-cli/default
    steps:
      - checkout
      - *restore_target
      - aws-cli/setup:
          profile-name: lambda
      - run: ./1-create-bucket.sh
      - run: ./2-deploy.sh
  test:
    docker:
      - image: circleci/openjdk:11-node
    steps:
      - checkout
      - run: mvn test
  build:
    docker:
      - image: circleci/openjdk:11-node
    steps:
      - checkout
      - run: mvn -Dmaven.test.skip=true package
      - store_artifacts:
          path: target/restaurant-scraper-1.0-SNAPSHOT.jar
      - run: echo "export CACHE_KEY=target_cache-$(date +%s)" >> $BASH_ENV
      - *cache_target
orbs:
  aws-cli: circleci/aws-cli@1.3.0
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-function:
          requires:
            - test
          filters:
            branches:
              only: master