version: 2.1

jobs:
  deploy-function:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: lambda
      - run: ./1-create-bucket.sh
      - run: ./2-deploy.sh
      - run: ./3-invoke.sh

  test:
    docker:
      - image: circleci/openjdk:11-node
    steps:
      - checkout
      - run: mvn test
      - store_artifacts:
          path: /target

  build:
    docker:
      - image: circleci/openjdk:11-node
    steps:
      - checkout
      - run: mvn -Dmaven.test.skip=true package

orbs:
  aws-cli: circleci/aws-cli@1.3.0

workflows:
  version: 2

  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-function:
          requires:
            - test